title @s[tag=!credit] title §l§aᴮᵃᵗᵗˡᵉᶜʳᵃᶠᵗ
playsound random.pop @s[tag=!credit]
tellraw @s[tag=!credit] {"rawtext":[{"text":"for help type /function help"}]}
tellraw @s[tag=!credit] {"rawtext":[{"text":"Guns /items Programmed by: §1DrTrash 250, §cJxcksonn, §r& §r§3Abdul Rahim"}]}
tellraw @s[tag=!credit] {"rawtext":[{"text":"Models by: §6KingZ, §aCheemNasour, §cJxcksonn, §7Onezawa, §3Daison,§r& §5Dabucks"}]}
tellraw @s[tag=!credit] {"rawtext":[{"text":"Animated by: §6KingZ §7& §cJxcksonn"}]}
tellraw @s[tag=!credit] {"rawtext":[{"text":"§7special thanks to: §bGabirel Aplok & Mano Galo§7/§3Hard love,§7 & §8MorningStar "}]}
tellraw @s[tag=!credit] {"rawtext":[{"text":"Founder: §l§2Venom69"}]}
tellraw @s[tag=!credit] {"rawtext":[{"text":"§2Enjoy the add-on!."}]}
/playsound random.pop @s[tag=!credit]
tag @s[tag=!credit] add credit