function reload/mac
function reload/fal
function reload/hk416
function reload/m16a2
function reload/m4a1
function reload/fn15
function reload/deagle
function reload/scar
function reload/aa12
function reload/tacm4
function reload/g36c
function reload/auga3
function reload/uzi
function reload/m1911
function reload/dm9
function reload/ak47
function reload/glock
function reload/vector
function reload/l96
function reload/revolver
function reload/m249
function reload/m24
function reload/m9
function reload/m590
function reload/scorpion